apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveperson-twitter-search
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: liveperson-twitter-search
          image: 001536788864.dkr.ecr.us-east-1.amazonaws.com/liveperson-twitter-search
          ports:
            - containerPort: 3000
