AWSTemplateFormatVersion: 2010-09-09

Description: >
  LivePerson twitter search cluster stack.

Resources:
  LivePersonTwitterSearchRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: liveperson-twitter-search
      Tags:
        - Key: Name
          Value: liveperson-twitter-search
